# Repo: org/project-xyz-infra
# File: .github/workflows/terraform-plan-on-pr.yml

name: Use central Terraform Plan on PR

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  terraform:
    uses: org/reusable/.github/workflows/terraform-plan-on-pr.yml@main
    with:
      tf_working_directory: "."   # oder z.B. "infra/terraform"
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
